server:
  error:
    include-stacktrace: on_param

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/anime?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: admin.2011
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        show_sql: true
        format_sql: true


logging:
  level:
    #root: DEBUG
    org.springframework.web: DEBUG
    #com.howtodoinjava: DEBUG
    #org.hibernate: DEBUG